### ISSUE TITLE
handle empty metrics in plot / plot_many

### ISSUE THREAD

**Issue by ikamensh** [ikamensh/pennpaper#4]
currently, an exception in averaging is thrown.

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/ikkamens/PycharmProjects/prio_train/train_plain.py", line 34, in <module>
    plot_group({"batch_loss": m_batch_loss, "training_set_loss": m_train_loss}, 'plots', name="usual")
  File "/Users/ikkamens/.pyenv/versions/3.7.3/lib/python3.7/site-packages/ilya_ezplot/plot/plot.py", line 52, in plot_group
    _plot(label, metric, stdev_factor = 0.7)
  File "/Users/ikkamens/.pyenv/versions/3.7.3/lib/python3.7/site-packages/ilya_ezplot/plot/plot.py", line 71, in _plot
    avg = apply_running_average(avg, smoothen)
  File "/Users/ikkamens/.pyenv/versions/3.7.3/lib/python3.7/site-packages/ilya_ezplot/processing/running_avg.py", line 15, in apply_running_average
    forward = _running_avg(data, smoothen)
  File "/Users/ikkamens/.pyenv/versions/3.7.3/lib/python3.7/site-packages/ilya_ezplot/processing/running_avg.py", line 6, in _running_avg
    result = [data[0]]
IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Comment by ikamensh** [comment]
resolved in v0.12
